def create():
    oxyfuel_cutting_width_file = "5" + "\n"
    oxyfuel_cutting_width_file += "1.2" + "\n"
    oxyfuel_cutting_width_file += "600" + "\n" + "\n"
    oxyfuel_cutting_width_file += "5" + "\n"
    oxyfuel_cutting_width_file += "10" + "\n"
    oxyfuel_cutting_width_file += "2" + "\n"
    oxyfuel_cutting_width_file += "520" + "\n" + "\n"
    oxyfuel_cutting_width_file += "10" + "\n"
    oxyfuel_cutting_width_file += "20" + "\n"
    oxyfuel_cutting_width_file += "2.3" + "\n"
    oxyfuel_cutting_width_file += "475" + "\n" + "\n"
    oxyfuel_cutting_width_file += "20" + "\n"
    oxyfuel_cutting_width_file += "30" + "\n"
    oxyfuel_cutting_width_file += "2.6" + "\n"
    oxyfuel_cutting_width_file += "400" + "\n" + "\n"
    oxyfuel_cutting_width_file += "30" + "\n"
    oxyfuel_cutting_width_file += "40" + "\n"
    oxyfuel_cutting_width_file += "3" + "\n"
    oxyfuel_cutting_width_file += "350" + "\n" + "\n"
    oxyfuel_cutting_width_file += "40" + "\n"
    oxyfuel_cutting_width_file += "60" + "\n"
    oxyfuel_cutting_width_file += "3.2" + "\n"
    oxyfuel_cutting_width_file += "290" + "\n" + "\n"
    oxyfuel_cutting_width_file += "60" + "\n"
    oxyfuel_cutting_width_file += "80" + "\n"
    oxyfuel_cutting_width_file += "3.5" + "\n"
    oxyfuel_cutting_width_file += "260" + "\n" + "\n"
    oxyfuel_cutting_width_file += "80" + "\n"
    oxyfuel_cutting_width_file += "125" + "\n"
    oxyfuel_cutting_width_file += "3.8" + "\n"
    oxyfuel_cutting_width_file += "220" + "\n" + "\n"
    oxyfuel_cutting_width_file += "125" + "\n"
    oxyfuel_cutting_width_file += "150" + "\n"
    oxyfuel_cutting_width_file += "4" + "\n"
    oxyfuel_cutting_width_file += "200" + "\n" + "\n"
    oxyfuel_cutting_width_file += "150" + "\n"
    oxyfuel_cutting_width_file += "100000000000" + "\n"
    oxyfuel_cutting_width_file += "4.5" + "\n"
    oxyfuel_cutting_width_file += "150" + "\n"
    
    oxyfuel_file = open(".gisoplox/oxyfuel_cutting_width.gisoplox", "w")
    oxyfuel_file.write(oxyfuel_cutting_width_file)
    oxyfuel_file.close()
