def create():
    plasma_cutting_width_file = "3" + "\n"
    plasma_cutting_width_file += "1.6" + "\n"
    plasma_cutting_width_file += "4900" + "\n" + "\n"
    plasma_cutting_width_file += "3" + "\n"
    plasma_cutting_width_file += "5" + "\n"
    plasma_cutting_width_file += "2" + "\n"
    plasma_cutting_width_file += "3800" + "\n" + "\n"
    plasma_cutting_width_file += "5" + "\n"
    plasma_cutting_width_file += "10" + "\n"
    plasma_cutting_width_file += "2.4" + "\n"
    plasma_cutting_width_file += "2700" + "\n" + "\n"
    plasma_cutting_width_file += "10" + "\n"
    plasma_cutting_width_file += "15" + "\n"
    plasma_cutting_width_file += "2.5" + "\n"
    plasma_cutting_width_file += "2000" + "\n" + "\n"
    plasma_cutting_width_file += "15" + "\n"
    plasma_cutting_width_file += "20" + "\n"
    plasma_cutting_width_file += "2.8" + "\n"
    plasma_cutting_width_file += "1200" + "\n" + "\n"
    plasma_cutting_width_file += "20" + "\n"
    plasma_cutting_width_file += "25" + "\n"
    plasma_cutting_width_file += "3.1" + "\n"
    plasma_cutting_width_file += "950" + "\n" + "\n"
    plasma_cutting_width_file += "25" + "\n"
    plasma_cutting_width_file += "30" + "\n"
    plasma_cutting_width_file += "3.6" + "\n"
    plasma_cutting_width_file += "600" + "\n" + "\n"
    plasma_cutting_width_file += "30" + "\n"
    plasma_cutting_width_file += "35" + "\n"
    plasma_cutting_width_file += "3.8" + "\n"
    plasma_cutting_width_file += "550" + "\n" + "\n"
    plasma_cutting_width_file += "35" + "\n"
    plasma_cutting_width_file += "40" + "\n"
    plasma_cutting_width_file += "4" + "\n"
    plasma_cutting_width_file += "400" + "\n" + "\n"
    plasma_cutting_width_file += "40" + "\n"
    plasma_cutting_width_file += "100000000000" + "\n"
    plasma_cutting_width_file += "4.2" + "\n"
    plasma_cutting_width_file += "150" + "\n"
    
    plasma_file = open(".gisoplox/plasma_cutting_width.gisoplox", "w")
    plasma_file.write(plasma_cutting_width_file)
    plasma_file.close()
