name: gisoplox
version: '0.23.0615'
summary: 'Simple CAM software for cutting machines'
description: |
  CAM software to generate G code for plasma and oxyfuel cutting machines
  that take advantage of already cutted edges.

grade: stable
confinement: strict
base: core18

apps:
    cli:
        command: python3 $SNAP/usr/lib/python3.8/Gisoplox-terminal.py
        plugs:
            - home
            - gsettings
    gisoplox:
        command: python3 $SNAP/usr/lib/python3.8/Gisoplox.py
        extensions: [gnome-3-28]
        plugs:
            - desktop
            - desktop-legacy
            - x11
            - home
            - gsettings
            - removable-media

parts:      
  source-copy:
    plugin: dump
    source: ./src
    organize:
      '*': usr/lib/python3.8/

  gisoplox:
    plugin: python
    python-version: python3
    source: ./src
    python-packages:
        - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl
    override-build: |
      pwd
      cd /lib/x86_64-linux-gnu
      ls
