name: gisoplox
version: '0.23.0615'
summary: 'Simple CAM software for cutting machines'
description: |
  CAM software to generate G code for plasma and oxyfuel cutting machines
  that take advantage of already cutted edges.

grade: stable
confinement: strict
base: core22
architectures:
  - build-on: amd64

apps:
  cli:
    command: python3 $SNAP/usr/lib/python3.10/Gisoplox-terminal.py
    plugs:
      - home
      - gsettings
      - removable-media
  gisoplox:
    command: python3 $SNAP/usr/lib/python3.10/Gisoplox.py
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - home
      - gsettings
      - removable-media

parts:
  source-copy:
    plugin: dump
    source: ./src
    organize:
      '*': usr/lib/python3.10/

  gisoplox:
    plugin: python
    source: ./src
    stage-packages:
        - libm
        - libc
    python-packages:
        - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
