name: gisoplox
version: '0.21.0215'
summary: 'Simple CAM software for cutting machines'
description: |
  CAM software to generate G code for plasma and oxyfuel cutting machines
  that take advantage of already cutted edges.

grade: stable
confinement: strict
base: core18

apps:
    cli:
        command: python3 $SNAP/usr/lib/python3.6/Gisoplox-terminal.py
        plugs: [home, gsettings]
    gisoplox:
        command: python3 $SNAP/usr/lib/python3.6/Gisoplox.py
        extensions: [gnome-3-28]
        plugs: [home, gsettings]

parts:
  source-copy:
    plugin: dump
    source: ./src
    organize:
      '*': usr/lib/python3.6/

  gisoplox:
    plugin: python
    python-version: python3
    source: ./src
    python-packages:
        - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.4-cp36-cp36m-linux_x86_64.whl
    requirements:
        - /root/project/requirements.txt
