name: Publish Gisoplox Edge

on:
  push:
    branches:
      - master
  workflow_dispatch: # or manually
    
jobs:
  publish_amd64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install snapcraft
      run: sudo snap install snapcraft --classic
    - name: build snap
      run: |
        sudo snapcraft --destructive-mode
        sudo rm -rf $HOME/.config/snapcraft
    - name: publish snap
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
      run: snapcraft upload --release=edge freecad*.snap
